# Using abreviated letter coding for group names. This will be used to parse these arguments when passed from command line.
# Example usage in command-line: --tmgr.epochs 10

# trainer arguments
trainer:
    max_train_steps_per_epoch : 20 # Maximum train steps per epoch.
    max_val_steps_per_epoch : 5 # Maximum validation steps per epoch.
    train_batch_size: 8 # Training global batch size.
    val_batch_size: 4 # Validation global batch size.
    epochs: 1 # Total epochs to run.
    gpu_batch_size_limit : 8 # Max limit for GPU batch size during training.
    clip_grads : False # Enable or disable clipping of gradients.
    use_gpu: True # Enable or disable use of GPU.
    max_grad_norm: 1.0 # Maximum value for gradient norm.
    writers: ['stdout', 'aml', 'tensorboard'] # List of all the writers to use.
    reset_optimizers_schedulers: True

# Checkpointer arguments
chkp:
    checkpoint: True # Flag indicating whether to checkpoint model.
    delete_existing_checkpoints: False # Flag indicating whether to delete checkpoints under save_dir before training.
    period: 1 # Period of epochs at which to checkpoint model.
    save_dir: 'checkpoints' # Path to directory where checkpoints are to be stored.
    #load_dir: 'checkpoints' # Path to directory where checkpoints are to be loaded from.
    #load_filename: 'tweetClassification_0.pt' # Filename of checkpoint under load_dir (overrides automatic loading of max epoch).
    file_prefix: 'tweetClassification' # Prefix of the checkpoint filename.
    file_ext: 'pt' # File extension for the checkpoint.
    log_level: 'DEBUG' # Log level for checkpointer module.

# Basic-Statistics arguments
stat:
    log_steps: 50 # Interval between steps for logging stats.
    update_system_stats: False # Enable or disable updating system stats
    log_model_steps: 1000 # Interval between steps for logging model.
    exclude_list: 'bias|LayerNorm|layer\\.[3-9]|layer\\.1(?!1)|layer\\.2(?!3)' # Exclude list for logging.

# Writers arguments
wrts:
    model_log_level : 'INFO' # Log level for model. Set to DEBUG to enable.
    tb_log_dir : 'logs' # Folder name for storing Tensorboard logs.
    tb_logpath_parent_env : null # Log path parent Environment.
    tb_log_multi : False # Enable or disable logging multi.
    tb_log_hist_steps : 20000 # Interval between steps to log histogram.

# Scenario-specific arguments
module:
    max_lr : 0.00004 # Maximum learning rate.
    log_level: 'INFO'

data:
    filepath_train: '../data/Corona_NLP_train.csv'
    filepath_test: '../data/Corona_NLP_test.csv'
    preprocessed_dir: '../preprocessed/'
    encoding: 'ISO-8859-1'
    text_field: 'OriginalTweet'
    label_field: 'Sentiment'
    splitpct: 10
    log_level: 'INFO'

meta:
    backend: 'sp'
