data_path: 'D:/data/cnn_cln'
trainer_class: 'SingleProcessAmp'
dist: False
cuda: 0

trainer:
    max_train_steps_per_epoch : 2 # Maximum train steps per epoch.
    max_val_steps_per_epoch : 2 # Maximum validation steps per epoch.
    train_batch_size: 1 # Training global batch size.
    val_batch_size: 1 # Validation global batch size.
    epochs: 3 # Total epochs to run.
    gpu_batch_size_limit : 16 # Max limit for GPU batch size during training.
    disable_tqdm : False
    writers: ["aml", "tensorboard"]

module:
    max_length_encoder : 128
    max_length_decoder : 128

wrt:
    tb_log_dir : 'logs'

stat:
    log_steps : 1
chkp:
    checkpoint : False
    delete_existing_checkpoints: True
    save_dir: 'checkpoints'
    load_dir: null

generate:
    max_length: 128
    do_sample : False
    num_beams : 1