# pipeline to publish marlin package to our internal feed
# https://medium.com/raa-labs/creating-a-pipeline-in-azure-devops-to-build-and-publish-python-packages-artifacts-ea2f99410e6c
trigger:
  branches:
    include: ['u/elr/refactor', 'master']
    
steps:
- task: UsePythonVersion@0  
  inputs:
    versionSpec: '3.7'  
  displayName: 'Use Python 3.7'
- script: |    
    python -m pip install --upgrade pip
  displayName: 'upgrade pip'
- script: |    
    python setup.py sdist 
  workingDirectory: sources/dev/SubstrateInferences/Marlin
  displayName: 'setup.py'
- task: CopyFiles@2  
  inputs:
    sourceFolder: sources/dev/SubstrateInferences/Marlin/dist    
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1  
  inputs:    
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'                  
    ArtifactName: 'dist'    
    publishLocation: 'Container'