glue_task: 'sst2'

mi:
    encoder : "bert-base-uncased"
    tokenizer: "bert-base-uncased"
    num_labels : 2
    max_lr : 0.0002
    max_length : 128
tr:
    max_train_steps_per_epoch : 100 # Maximum train steps per epoch.
    max_val_steps_per_epoch : null # Maximum validation steps per epoch.
    train_batch_size: 32 # Training global batch size.
    val_batch_size: 4 # Validation global batch size.
    epochs: 10 # Total epochs to run.
    gpu_batch_size_limit : 4 # Max limit for GPU batch size during training.
    disable_tqdm : False
    writers: ['stdout', 'aml', 'tensorboard']
    backend: 'ddp-dp'

opacus:
    sample_rate: 0.0001 #0.0004
    batch_size: null
    sample_size: null
    max_grad_norm: 1.0
    noise_multiplier: 0.8
    #alphas: List[float] = DEFAULT_ALPHAS,  Removed since default lies in Privacy engine
    secure_rng: False
    batch_first: True
    target_delta: 0.000006
    target_epsilon: null #Float
    epochs: null #int
    loss_reduction: "mean" #Indicates if the loss reduction (for aggregating the gradients) is a sum or a mean operation. Can take values "sum" or "mean"
    poisson: False

wrt:
    tb_log_dir : 'logs_roberta_base/sst2/from_pretrained'

stat:
    log_steps : 20
dist:
    local_rank : 1
ckp:
    checkpoint : False
    period: 2