/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  docsSidebar: [
    'getting-started', 
    'installation', 
    'marlin-in-pictures',
    {'Examples': [{type: 'autogenerated', dirName: 'examples'}]},
    {'Plugins': [{type: 'autogenerated', dirName: 'plugins'}]},
    'utils/stats',
    'credits'
  ],
  // pydoc-markdown auto-generated markdowns from docstrings
  referenceSideBar: [require("./docs/reference/sidebar.json")]
};
