FROM mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04

##############################################################################
# Custom Conda environment
##############################################################################

ENV CONDAPATH /opt/miniconda/envs/pymarlin
RUN conda create -p $CONDAPATH python=3.8 pip=20.2.4
ENV PATH $CONDAPATH/bin:$PATH

##############################################################################
# PyTorch
##############################################################################

RUN pip install --no-cache-dir torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

################################################################################################
# pymarlin[plugins] should have everything needed to run classification
################################################################################################

RUN pip install --no-cache-dir --use-feature=2020-resolver pymarlin[plugins]
